### PR TITLE
Implemented natively styled WPF control for status displaying on StatusBar

### PR DESCRIPTION
**Pull request by xperiandri**
@madskristensen pay attention to https://github.com/xperiandri/DialToolsForVS/blob/ee739848e7398b34bf832587a543db621f6692b1/src/Themes/Generic.xaml#L13
If it is possible ask Team Explorer team why do they set these properties manually and not inherit values from container (FontSize 12)

@madskristensen if it is possible ask Shell UI team if Automation approach is better https://github.com/xperiandri/DialToolsForVS/blob/ee739848e7398b34bf832587a543db621f6692b1/src/Controller/StatusbarInjector.cs#L30

@OmerRaviv could you please make a review of package initialization and threading?
I will appreciate if you advise how to measure performance impact onto Visual Studio startup time and UI responsiveness by this extension initialization.

### CODE REVIEW

**Comment by madskristensen** [comment]
This looks great. Let me know when it is ready to merge.

**Comment by xperiandri** [comment]
Maybe @OmerRaviv can advise what is better Visual Tree traversal or Logical Tree traversal using Automation?

**Comment by xperiandri** [comment]
Let's merge and release a new version of the extension.
If I find a way to add any improvements they will go to next PR.

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
