### PR TITLE
Fixed issue with new Welcome screen

### PR DESCRIPTION
**Pull request by xperiandri**
When controller initialization crushed if the main window is not open immediately after welcome window.
And issue #30 and probably #32.
Fixed issue with incorrect Window releasing and activating in ErrorsController and BookmarksController.
Updated NuGet packages to the latest 15.x versions.
Updated target Windows platform to 10.0.18362.0

### CODE REVIEW

**Comment by xperiandri** [comment]
@madskristensen, please, review and issue an updated package

**Comment by madskristensen** [comment]
awesome. Thanks!!

**Comment by xperiandri** [comment]
@madskristensen issue an updated package, please.

**Comment by madskristensen** [comment]
@xperiandri I don't understand. Are you asking for a new release to the VS Marketplace?

**Comment by xperiandri** [comment]
Yes

**Comment by madskristensen** [comment]
Done, give it five minutes to go through the Marketplace validation before it is live

**Comment by xperiandri** [comment]
Thanks

**Pull request merged**
