### PR TITLE
Finally fixed issue with status bar icon initialization code crash when main window is not yet loaded

### PR DESCRIPTION
**Pull request by xperiandri**
@madskristensen, please, issue a new package to Visual Studio Gallery for this update

### CODE REVIEW

**Comment by xperiandri** [comment]
This PR fixes scenario when you wait on a welcome screen too long.
In that case, `KnownUIContexts.ShellInitializedContext.WhenActivated` calls its callback even though the main window has not yet initialized and WPF visual tree is not yet ready

**Comment by madskristensen** [comment]
Awesome. Thank you!!

**Comment by xperiandri** [comment]
@madskristensen release a new version of the package to the store, please

**Comment by madskristensen** [comment]
@xperiandri pulishing now...

**Pull request merged**
