### PR TITLE
Massive rework to async load

### LINKED ISSUE #18: Radial control is not recognized in editor window moved out of main window
### Installed product versions
- Visual Studio: 15.5.2 Enterprise
- This extension: 0.7.46

### Description
If you have [Double-Click Maximize](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.Double-ClickMaximize) and maximize editor with double click then radial control do not function in it (no menu items appear).

### Steps to recreate
1. Drag editor outside the main Visual Studio window
2. Hold radial control to display it's menu

### Current behavior
No Visual Studio specific items appear

### Expected behavior
Visual Studio specific menu items appear and function the same as in the main window

### PR DESCRIPTION
**Pull request by xperiandri**
Made on top of #15 
Initial work made to fix #18

### CODE REVIEW

**Comment by xperiandri** [comment]
@bjorndaniel, @bjorndaniel, please, try this branch to check if everything works as expected.

You can also play with tasks priority to fasten extension load.
Look for `ThreadHelper.JoinableTaskFactory.StartOnIdle`

**Comment by bjorndaniel** [comment]
So you did the async load, cool! I was gonna try that to learn how to, I guess I'll have to write an entire new extension to learn this now :)
I have tried it now and I found 2 things not working:

- Since you have renamed the Project and default namespace 
```
const string resourceName = "DialToolsForVS.Resources.commands.txt";
```
needs to be changed to
```
const string resourceName = "DialControllerTools.Resources.commands.txt";
```

- The ImmutableArray still causes a crash. I read this from the team:
https://blogs.msdn.microsoft.com/dotnet/2013/06/24/please-welcome-immutablearrayt/
and if you change the property to:
```
 private ImmutableArray<string> Commands
         => commands.IsDefaultOrEmpty
            ? commands = VsCommands.ParseCommands(commandsString)
            : commands;
```
it works as expected without the messy initialization I was doing.
I found a small thing with the text selection in the commands box, but I can fix that once this PR is in, it is easy enough to work around by just resizing the window a bit.

**Comment by xperiandri** [comment]
Cool, thanks! I will fix that.

Could you post a screenshot of the command box issue?

**Comment by madskristensen** [comment]
This is awesome. Let me know when this is ready to merge.

**Comment by bjorndaniel** [comment]
If you change the clicked event in the command box to this
```
   private void CommandsBox_MouseClick(object sender, MouseEventArgs e)
        {
            var current_line = CommandsBox.GetLineFromCharIndex(CommandsBox.SelectionStart);
            _selectedText = CommandsBox.Lines[current_line];
            CommandsBox.SelectionStart = CommandsBox.GetFirstCharIndexFromLine(current_line);
            CommandsBox.SelectionLength = _selectedText?.Length ?? 0;
        }
```
it will solve the issue, it was a bug where I had selected the length of the previously selected line instead of the current...

**Comment by bjorndaniel** [comment]
@xperiandri I have been using this for a while now and I think it is ready to be merged, what do you think?

**Comment by xperiandri** [comment]
I haven't tried all the options but it works fine.
By the way, have you checked if it orders items correctly?

**Comment by xperiandri** [comment]
Indeed, the order is not preserved

**Pull request merged**
